name: Deploy Fullstack App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::760971381013:role/GitHubDeployRole
          aws-region: ap-southeast-2

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub CI/CD Deploy to EC2" \
            --targets "Key=InstanceIds,Values=i-08b457aa622a9488f" \
            --parameters 'commands=["/home/ec2-user/app/deploy.sh"]' \
            --region ap-southeast-2
